apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm-cirros
  labels:
    app: testvm
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/vm: testvm-cirros
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 128Mi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: testvm
              password: password
              chpasswd:
                expire: false
