apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-from-dv
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-from-dv
    spec:
      domain:
        devices:
          disks:
            - name: datavolumedisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 128Mi
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
        - name: datavolumedisk
          persistentVolumeClaim:
            claimName: cirros-dv
